Add persistent navigation bar to webapp
AcademyofCleaning/AcademyofCleaning pull request #12
Opened 2020-11-06 21:35 UTC by matthewfollegot

This PR adds a persistent and responsive navigation bar to the application that can be viewed on each respective view that has been implemented.

- [x] pushed to Heroku
- [x] persistent nav bar
- [x] contains key tabs for searching users and viewing my profile

*Note to reviewer: squash commits upon merge*

2020-11-06 21:37 UTC, matthewfollegot commented
![](https://github.trello.services/images/mini-trello-icon.png) [NavBar persisting above the webapp/Global CSS [3 SP]](https://trello.com/c/4NCianlH/41-navbar-persisting-above-the-webapp-global-css-3-sp)

2020-11-07 01:25 UTC, nicolasabousawan commented
This ticket should include default css for the entire react app... I don't see where those changes are. Global fonts and sizing should be set up by this ticket so we have some sort of baseline for all components. 
Did I miss this somewhere?

2020-11-07 01:26 UTC, nicolasabousawan requested changes
Missing Global CSS features?  See previous comment

2020-11-07 02:06 UTC, matthewfollegot commented
> This ticket should include default css for the entire react app... I don't see where those changes are. Global fonts and sizing should be set up by this ticket so we have some sort of baseline for all components.
> Did I miss this somewhere?

Sorry, this wasn't explicitly mentioned in the ticket's AC and I just so happened to leave the sprint planning early so I didn't have context. I'll add it explicitly to the AC and work on that.

2020-11-07 05:05 UTC, nicolasabousawan commented
![image](https://user-images.githubusercontent.com/37027135/98432507-c302ca80-2073-11eb-91cb-f62f4e9c38c4.png)

Very Nice

2020-11-07 05:10 UTC, nicolasabousawan requested changes

2020-11-07 05:10 UTC, nicolasabousawan commented on ui/README.md
> -### `npm run eject`
Why did we delete this? Do we no longer need it?

2020-11-07 05:10 UTC, nicolasabousawan commented on ui/src/App.js
> +        <Route exact path="/profiles/create">
Love the RESTful set up ;)

2020-11-07 05:10 UTC, nicolasabousawan commented on ui/src/Components/ProfilePage.jsx
> +          {!this.state.profile ? (
Good catch separating the 2 states

2020-11-07 05:10 UTC, nicolasabousawan commented on ui/src/Components/ProfilePage.jsx
> +              {/* <FormGroup row>
Is this supposed to be deleted?

2020-11-07 05:24 UTC, nicolasabousawan commented on ui/README.md
> -### `npm run eject`
spoke offline with  @matthewfollegot , this is indeed not needed

2020-11-07 05:25 UTC, nicolasabousawan approved these changes

2020-11-07 05:25 UTC, merged