LMS Page
AcademyofCleaning/AcademyofCleaning pull request #30
Opened 2020-12-03 02:12 UTC by nicolasabousawan

This is a place holder route the will contain sample videos that the cleaner can access.

- [ ] Access via /learn 
- [ ] Format/CSS is as per standards (2+ SEs must agree)
- [ ] placeholder content is easily replaceable with new content (technical requirement)

2020-12-04 22:18 UTC, gurleen-sanghera requested changes
- Access via /learn: this looks good, I like the rerouting back to home too :)
-  Format/CSS is as per standards (2+ SEs must agree): this is a bit inconsistent, I left comments with pictures
 - placeholder content is easily replaceable with new content (technical requirement): I read up on iFrames and looks like removing the link + certain addition code you added (allowing for fullscreen, etc.) and replacing with new content is very doable. Since we don't know how they want this to be formatted though, I don't think this point is too much of an issue.

2020-12-04 22:18 UTC, gurleen-sanghera commented on ui/src/Components/Learn.jsx
> +            <h3> Start Learning Here! </h3>
I think you need to add some customized CSS. All other pages are more cohesive in terms of the titles and text. 
![image](https://user-images.githubusercontent.com/43486058/101220163-338d0f00-3653-11eb-80d6-717e3062b7e3.png)
![image](https://user-images.githubusercontent.com/43486058/101220717-29b7db80-3654-11eb-91c6-4c744ed844d9.png)

^ This shows the titles and text on other pages and how they follow the same styling vs the below shows the titles/text in the LMS

![image](https://user-images.githubusercontent.com/43486058/101220785-4ce28b00-3654-11eb-9dc3-3b129b0417cb.png)
![image](https://user-images.githubusercontent.com/43486058/101220791-4fdd7b80-3654-11eb-8655-9a8d0915599a.png)

2020-12-05 00:02 UTC, nicolasabousawan commented
Yes @gurleen-sanghera good call out, forgot to push my changes. The Title now matches the same font as all title pages. The captions now match the same font as the labels of the form (i.e first name in /create) 
If we both sign off on this and get @kvptkr to approve the design, we should be good to merge.

2020-12-05 21:15 UTC, kvptkr commented
@nicolasabousawan could you just make sure you deploy it and things are working and then I can approve things 😄

2020-12-06 20:03 UTC, gurleen-sanghera reviewed
Looks good Nicolas!

2020-12-06 20:04 UTC, gurleen-sanghera approved these changes

2020-12-06 21:37 UTC, merged